language: java
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.m2
install: true
script:
  - mvn clean install -Dgpg.skip=true -Dmaven.javadoc.skip=true -Dmaven.source.skip
  - bash <(curl -s https://codecov.io/bash)
